# my-project/docker-compose.yml

services:
  golem-node:
    build:
      context: ./golem-workers
    environment:
      YAGNA_AUTOCONF_APPKEY: ${YAGNA_AUTOCONF_APPKEY}
      YAGNA_API_URL: ${YAGNA_API_URL}
      GSB_URL: ${GSB_URL}
    command: yagna service run
    volumes:
      - yagna-data:/root/.local/share/yagna
    ports:
      - "7465:7465"

  web:
    build:
      context: ./golem-workers
    environment:
      YAGNA_APPKEY: ${YAGNA_APPKEY}
      YAGNA_API_URL: http://golem-node:7465
      GSB_URL: tcp://golem-node:7464
      GLOBAL_CONTEXTS: ${GLOBAL_CONTEXTS}
    ports:
      - "8000:8000"
      - "8080:8080"
      - "8081:8081"

  node-server:
    build:
      context: ./node-server
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - golem-node

volumes:
  yagna-data:
