# my-smart-contract-project/docker-compose.yml

services:
  golem-node:
    build:
      context: ./golem-workers
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      YAGNA_AUTOCONF_APPKEY: ${YAGNA_AUTOCONF_APPKEY}
      YAGNA_API_URL: ${YAGNA_API_URL}
      GSB_URL: ${GSB_URL}
    command: yagna service run
    volumes:
      - yagna-data:/root/.local/share/yagna
    ports:
      - "7465:7465"

  web:
    build:
      context: ./golem-workers
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      YAGNA_APPKEY: ${YAGNA_APPKEY}
      YAGNA_API_URL: http://golem-node:7465
      GSB_URL: tcp://golem-node:7464
      GLOBAL_CONTEXTS: ${GLOBAL_CONTEXTS}
    ports:
      - "8000:8000"
      - "8080:8080"
      - "8081:8081"

  node-server:
    build:
      context: ./node-server
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      PRIVATE_KEY: ${PRIVATE_KEY}
      PRIVATE_RPC_URL: ${PRIVATE_RPC_URL}
      API_KEY: ${API_KEY}
    ports:
      - "3000:3000"
    depends_on:
      - golem-node
      - worker

  worker:
    build:
      context: ./golem-workers
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      PRIVATE_KEY: ${PRIVATE_KEY}
      PRIVATE_RPC_URL: ${PRIVATE_RPC_URL}
      API_KEY: ${API_KEY}
    ports:
      - "8001:8000"  # Porta esterna diversa se necessario
    depends_on:
      - golem-node

volumes:
  yagna-data: