name: SmartBugs Analysis

on:
 workflow_dispatch:
    inputs:
      contractCode:
        description: "Codice del contratto Solidity da analizzare"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Scrivi il contratto ricevuto in un file
        run: |
          echo "${{ github.event.inputs.contractCode }}" > contracts/Contract.sol

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install SmartBugs
        run: |
          git clone https://github.com/smartbugs/smartbugs.git
          cd smartbugs
          ./install/setup-venv.sh

      - name: Run SmartBugs
        run: |
          cd smartbugs
          ../smartbugs/smartbugs -t all -f ../contracts/*.sol --processes 2 --mem-limit 4g --timeout 600
          ../smartbugs/reparse results
          ../smartbugs/results2csv -p results > ${{ github.workspace }}/results.csv  # Salva i risultati nella root del tuo repo
          
      - name: List root directory contents
        run: ls -la ${{ github.workspace }}  # Elenca il contenuto della root del tuo repo
        
      - name: Upload Results to Pinata
        run: |
          curl -v -X POST "https://api.pinata.cloud/pinning/pinFileToIPFS" \
            -H "Authorization: Bearer ${{ secrets.PINATA_JWT }}" \
            -F "file=@${{ github.workspace }}/results.csv"  # Fa l'upload del file results.csv dalla root del repo
