name: SmartBugs Analysis

on:
  push:
    paths:
      - 'contracts/*.sol'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get the latest modified .sol file
        id: get_latest_file
        run: |
          # Trova l'ultimo file .sol modificato nella cartella contracts
          latest_file=$(git log -1 --name-only --pretty=format: | grep '^contracts/.*\.sol$')
          echo "LATEST_FILE=${latest_file}" >> $GITHUB_ENV

      - name: Install SmartBugs
        run: |
          git clone https://github.com/smartbugs/smartbugs.git
          cd smartbugs
          ./install/setup-venv.sh

      - name: Run SmartBugs
        run: |
          cd smartbugs
          # Assicurati che LATEST_FILE sia utilizzato correttamente
          if [ -n "${{ env.LATEST_FILE }}" ]; then
            ../smartbugs/smartbugs -t all -f ../${{ env.LATEST_FILE }} --processes 2 --mem-limit 4g --timeout 600
            ../smartbugs/reparse results
            ../smartbugs/results2csv -p results > ${{ github.workspace }}/results.csv
          else
            echo "No .sol files found in the latest commit."
            exit 1
          fi

      - name: List root directory contents
        run: ls -la ${{ github.workspace }}

      - name: Upload Results to Pinata
        run: |
          curl -v -X POST "https://api.pinata.cloud/pinning/pinFileToIPFS" \
            -H "Authorization: Bearer ${{ secrets.PINATA_JWT }}" \
            -F "file=@${{ github.workspace }}/results.csv"
