name: SmartBugs Analysis

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install SmartBugs
        run: |
          git clone https://github.com/smartbugs/smartbugs.git
          cd smartbugs
          ./install/setup-venv.sh

      - name: Run SmartBugs
        run: |
          cd smartbugs
          ../smartbugs/smartbugs -t all -f ../contracts/*.sol --processes 2 --mem-limit 4g --timeout 600
          ../smartbugs/reparse results
          ../smartbugs/results2csv -p results > results.csv

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: smartbugs/results.csv
